spring.application.name=campus-canteen
server.port=8080

# =======================================================
# MySQL Database Configuration
# =======================================================
spring.datasource.url=jdbc:mysql://localhost:3306/campus_canteen?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# =======================================================
# Thymeleaf & Web Settings
# =======================================================
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8